"""add monthly_investing_goal to settings

Revision ID: 0a8ad919d283
Revises: 13cd86524e84
Create Date: 2026-05-28 12:32:04.373266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8ad919d283'
down_revision = '13cd86524e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_investing_goal', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('monthly_investing_goal')

    # ### end Alembic commands ###
