"""add monthly_contribution to goals

Revision ID: 13cd86524e84
Revises: 6253db890ead
Create Date: 2026-05-28 11:42:43.790563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13cd86524e84'
down_revision = '6253db890ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_contribution', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('monthly_contribution')

    # ### end Alembic commands ###
