"""add recurring expenses

Revision ID: 6253db890ead
Revises: fd00d10ec326
Create Date: 2026-05-26 15:01:47.429799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6253db890ead'
down_revision = 'fd00d10ec326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('auto_add', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurring_expenses')
    # ### end Alembic commands ###
